name: symbol_sdk
description: Symbol and Nem sdk for Dart and Flutter
version: 1.0.16
license: MIT
repository: https://github.com/0x070696E65/symbol_sdk.git

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  tuple: ^2.0.0
  base32: ^2.1.3
  bip39_mnemonic: ^3.0.6
  pointycastle: ^3.2.0
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.25.2
